name: Build And Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: | 
       git config user.name "$GITHUB_ACTOR"
       git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
       npm install
       npm run build
       cd dist
       echo 'casualconsulting.de' > CNAME
       git init
       git add -A
       git commit -m 'deploy'
       git push -f https://${GITHUB_ACTOR}:${GH_PERSONAL_ACCESS_TOKEN}@github.com/$GITHUB_REPOSITORY.git master:gh-pages
       cd -
